<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260319194445 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE search_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, query VARCHAR(255) NOT NULL, found BOOLEAN DEFAULT false NOT NULL, duration_ms INT DEFAULT NULL, ip_anonymized VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_search_log_created_at ON search_logs (created_at)');
        $this->addSql('CREATE TABLE transactions_lookup (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, raw_input VARCHAR(255) NOT NULL, normalized_input VARCHAR(255) NOT NULL, company_name VARCHAR(255) NOT NULL, description TEXT NOT NULL, category VARCHAR(100) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, confidence_level VARCHAR(20) NOT NULL, source VARCHAR(20) NOT NULL, hit_count INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D15C1D7D989D9B62 ON transactions_lookup (slug)');
        $this->addSql('CREATE INDEX idx_normalized_input ON transactions_lookup (normalized_input)');
        $this->addSql('CREATE INDEX idx_slug ON transactions_lookup (slug)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE search_logs');
        $this->addSql('DROP TABLE transactions_lookup');
    }
}
